// Generated by scripts/gen_errors.py from design/errors.json. Do not edit. Change the JSON and run the script.

package app.ferry

// Words for every error Ferry can show, from design/errors.json. Each
// code maps to three parts, in order: what stopped, why, what to do.
object FerryErrors {
    // One error code's three parts.
    data class Words(val stopped: String, val why: String, val todo: String)

    private val table: Map<String, Words> = mapOf(
        "AdbError::Failed" to Words("USB is unavailable.", "adb reported an error.", "Unplug and replug the cable. Check that USB debugging is on."),
        "AdbError::Io" to Words("USB is unavailable.", "adb could not be run.", "Reinstall Android platform tools."),
        "AdbError::NotFound" to Words("USB is unavailable.", "adb was not found on this Mac.", "Install Android platform tools, or use Wi-Fi."),
        "AdbError::RelativeBinary" to Words("USB is unavailable.", "adb was found by a relative path, which Ferry refuses.", "Install Android platform tools in the standard place."),
        "AdbError::Timeout" to Words("USB is unavailable.", "adb did not answer in ten seconds.", "Unplug and replug the cable."),
        "AdbError::Unparseable" to Words("USB is unavailable.", "adb answered in a form Ferry does not understand.", "Update Android platform tools."),
        "ChunkSizeError::NotPowerOfTwo" to Words("Ferry has a fault.", "The chunk size is not one BLAKE3 accepts.", "Report this. Nothing you did caused it."),
        "ChunkSizeError::TooLarge" to Words("Ferry has a fault.", "The chunk size is not one BLAKE3 accepts.", "Report this. Nothing you did caused it."),
        "ChunkSizeError::TooSmall" to Words("Ferry has a fault.", "The chunk size is not one BLAKE3 accepts.", "Report this. Nothing you did caused it."),
        "DiscoveryError::Mdns" to Words("Wi-Fi discovery is unavailable.", "The network refused multicast.", "Use the cable, or a different network."),
        "DiscoveryError::NoRandomness" to Words("Wi-Fi discovery is unavailable.", "This device gave no random data.", "Restart Ferry."),
        "FrameError::Io" to Words("The connection failed.", "The network dropped it.", "It reconnects on its own when the device is reachable."),
        "FrameError::PayloadTooLarge" to Words("The connection failed.", "The device sent a message larger than Ferry accepts.", "Update Ferry on both devices."),
        "FrameError::UnknownKind" to Words("The connection failed.", "The device sent a message this version does not know.", "Update Ferry on both devices."),
        "FrameError::Wire" to Words("The connection failed.", "A message could not be decoded.", "Update Ferry on both devices."),
        "ManifestError::BadChunkSize" to Words("The transfer could not resume.", "Its saved record is damaged.", "Start it again. It begins from zero."),
        "ManifestError::RootMismatch" to Words("The transfer could not resume.", "Its saved record was changed by something else.", "Start it again. It begins from zero."),
        "ManifestError::TooManyChunks" to Words("The transfer could not resume.", "Its saved record is damaged.", "Start it again. It begins from zero."),
        "ManifestError::Wire" to Words("The transfer could not resume.", "Its saved record is damaged.", "Start it again. It begins from zero."),
        "ManifestError::WrongChunkCount" to Words("The transfer could not resume.", "Its saved record is damaged.", "Start it again. It begins from zero."),
        "NoiseError::BadHandshakePayload" to Words("Pairing stopped.", "The other device sent a malformed handshake.", "Try again. If it repeats, update Ferry on both devices."),
        "NoiseError::BadHello" to Words("Pairing stopped.", "The scanning device sent a malformed name.", "Try again. If it repeats, update Ferry on both devices."),
        "NoiseError::BadKeyLength" to Words("The stored key is unusable.", "It is not the size Ferry expects.", "Forget every device and pair again. The key is made fresh."),
        "NoiseError::BadPattern" to Words("Ferry has a fault.", "An internal setting is wrong.", "Report this. Nothing you did caused it."),
        "NoiseError::CommitmentMismatch" to Words("Pairing stopped.", "The other device changed its identity during pairing. This can mean someone on the network interfered.", "Do not confirm. Try again on a network you trust, or over the cable."),
        "NoiseError::Crypto" to Words("The connection was refused.", "The handshake failed.", "If this keeps happening, forget the device and pair again."),
        "NoiseError::HandshakeMessageTooLarge" to Words("The connection was refused.", "The other end sent a handshake larger than Ferry accepts.", "Check that the other end is Ferry."),
        "NoiseError::Io" to Words("The connection failed.", "The network dropped it.", "It reconnects on its own when the device is reachable."),
        "NoiseError::MissingPeerKey" to Words("Pairing stopped.", "The other device sent no key.", "Try again."),
        "NoiseError::UnknownOffer" to Words("The scan was refused.", "The code is stale, or this Mac is not showing one to scan right now.", "Show the QR code again on the Mac, then scan it within two minutes."),
        "OpError::AlreadyExists" to Words("The folder was not created.", "Something with that name already exists.", "Choose another name."),
        "OpError::Internal" to Words("The operation failed.", "The device reported an error it could not explain.", "Try again. If it happens again, restart Ferry on that device."),
        "OpError::InvalidPath" to Words("The path was refused.", "It holds characters Ferry does not accept.", "Rename the file with a plain name."),
        "OpError::IsADirectory" to Words("The file could not be read.", "That path is a folder, not a file.", "Choose a file."),
        "OpError::NotADirectory" to Words("The folder could not be opened.", "That path is a file, not a folder.", "Choose a folder."),
        "OpError::NotEmpty" to Words("The folder was not deleted.", "It still holds files.", "Delete the files inside it first."),
        "OpError::NotFound" to Words("The file was not found.", "It is no longer at that path.", "Refresh and try again."),
        "OpError::PermissionDenied" to Words("The file could not be accessed.", "The device refused access to it.", "Check the shared folder setting on that device."),
        "OpError::RangeTooLarge" to Words("The request was refused.", "It asked for more than one message may carry.", "Update Ferry on both devices."),
        "OpError::Unsupported" to Words("The item was skipped.", "It is not a regular file or a folder.", "Nothing to do. Ferry serves files and folders only."),
        "PairingError::AlreadyPaired" to Words("The scan was refused.", "This device already holds a key for that Mac.", "Nothing to do. The two devices are already paired."),
        "PairingError::CameraRefused" to Words("The scan was refused.", "The camera permission was refused.", "Turn on the camera permission for Ferry, or pair by code instead."),
        "PairingError::OfferExpired" to Words("The scan was refused.", "The QR code is more than two minutes old.", "Show the QR code again on the Mac, then scan it within two minutes."),
        "PairingError::OfferNotFerry" to Words("The scan was refused.", "The scanned code is not a Ferry pairing code.", "Scan the QR code shown on the Mac's pairing screen."),
        "PathError::Absolute" to Words("The path was refused.", "It starts with a slash.", "Rename the file with a plain name."),
        "PathError::Backslash" to Words("The path was refused.", "It holds a backslash.", "Rename the file with a plain name."),
        "PathError::CurrentComponent" to Words("The path was refused.", "It holds a dot component.", "Rename the file with a plain name."),
        "PathError::Empty" to Words("The path was refused.", "It is empty.", "Rename the file with a plain name."),
        "PathError::NulByte" to Words("The path was refused.", "It holds a NUL character.", "Rename the file with a plain name."),
        "PathError::ParentComponent" to Words("The path was refused.", "It tries to go up a folder.", "Rename the file with a plain name."),
        "PathError::TooLong" to Words("The path was refused.", "It is longer than 1024 bytes.", "Rename the file with a plain name."),
        "PeerError::BadKey" to Words("The device list could not be read.", "It holds a key of the wrong size.", "Forget every device and pair again."),
        "PeerError::Io" to Words("The device list could not be saved.", "This device refused to write the file.", "Check free space."),
        "PeerError::NameTooLong" to Words("The name was refused.", "It is longer than 256 bytes.", "Choose a shorter name."),
        "PeerError::NoRandomness" to Words("The device list could not be saved.", "This device gave no random data.", "Restart Ferry."),
        "PeerError::TooMany" to Words("The device was not added.", "Ferry holds at most 64 paired devices.", "Forget one you no longer use."),
        "PeerError::UnknownFormat" to Words("The device list could not be read.", "It was written by a different version.", "Forget every device and pair again."),
        "PeerError::Wire" to Words("The device list could not be read.", "Its file is damaged.", "Forget every device and pair again."),
        "RootsError::NoRoots" to Words("Nothing is shared.", "The list of shared folders is empty.", "Add at least one folder."),
        "RootsError::RootNameInvalid" to Words("The shared folders were not set.", "A folder's name must be 1 to 64 bytes. It must hold no slash. It must hold no backslash. It must hold no control character. It must not be a dot. It must not be two dots.", "Give the folder a plain name and try again."),
        "RootsError::RootNameTaken" to Words("The shared folders were not set.", "Two folders were given the same name, ignoring case.", "Give each folder a different name."),
        "RootsError::RootNotAFolder" to Words("The shared folders were not set.", "A folder's path is not an existing folder.", "Choose a folder that exists."),
        "RootsError::RootOverlaps" to Words("The shared folders were not set.", "Two folders are the same, or one is inside the other.", "Choose folders that do not overlap."),
        "RpcError::BadName" to Words("The name was refused.", "It is empty, longer than 64 bytes, or holds a control character.", "Choose a plain name of up to 64 characters."),
        "RpcError::Frame" to Words("The connection failed.", "The network dropped it.", "It reconnects on its own when the device is reachable."),
        "RpcError::MismatchedRequestId" to Words("The connection failed.", "The device answered the wrong request.", "It reconnects on its own. If it repeats, update Ferry on both devices."),
        "RpcError::Remote" to Words("The device refused the request.", "Ferry does not know why.", "Try again."),
        "RpcError::UnexpectedFrameKind" to Words("The connection failed.", "The device sent a message out of order.", "It reconnects on its own. If it repeats, update Ferry on both devices."),
        "RpcError::Wire" to Words("The connection failed.", "A message could not be decoded.", "Update Ferry on both devices."),
        "Runtime::AllFilesAccess" to Words("Ferry cannot read the shared folders.", "All files access is not granted.", "Grant all files access in Settings."),
        "Runtime::BadConfig" to Words("Ferry could not start.", "{detail}", "Check the settings."),
        "Runtime::FolderTooLarge" to Words("The folder was not copied.", "It holds more than 10,000 files, or is nested more than 32 folders deep.", "Copy a smaller folder, or open it and copy fewer files at a time."),
        "Runtime::MountFailed" to Words("The Finder mount did not start.", "{detail}", "Try again. If it keeps failing, restart Ferry."),
        "Runtime::NameTooLong" to Words("The name was refused.", "It is longer than 64 bytes.", "Choose a shorter name."),
        "Runtime::NetworkName" to Words("The Wi-Fi network was not trusted.", "The name is empty or over 32 bytes, or the list is full.", "Use a shorter name. Forget a trusted Wi-Fi network first."),
        "Runtime::NoCandidate" to Words("Nothing was picked.", "That candidate is no longer present.", "Pick another."),
        "Runtime::NoRandomness" to Words("The QR code could not be made.", "The system supplied no randomness.", "Try again, or pair by code instead."),
        "Runtime::NotPaired" to Words("The device is not paired.", "Its key is not in this device's list.", "Pair it first."),
        "Runtime::NotReachable" to Words("The device is not reachable.", "It is not on the network and not on the cable.", "Bring it onto the same Wi-Fi, or plug it in."),
        "Runtime::NotStarted" to Words("Ferry is not running.", "The engine was not started.", "Restart Ferry."),
        "Runtime::PairingBusy" to Words("Pairing did not start.", "Another pairing is in progress.", "Finish or cancel it first."),
        "Runtime::PairingTimeout" to Words("Pairing stopped.", "No device appeared within two minutes.", "Turn pairing on for the other device and try again."),
        "Runtime::PushInFlight" to Words("The file was not sent.", "A push to that name on that device is already in progress.", "Wait for it to finish, then try again."),
        "Runtime::TransferNotFound" to Words("The transfer was not found.", "It is no longer in the list.", "Nothing to do."),
        "Runtime::WriteTooLarge" to Words("The file was not saved.", "One write carried more than 1 MiB. Ferry writes 1 MiB at a time.", "Save the file again."),
        "TcpError::Io" to Words("The connection failed.", "The network dropped it.", "It reconnects on its own when the device is reachable."),
        "TcpError::Noise" to Words("The connection was refused.", "The device did not prove it is the one paired.", "If this keeps happening, forget the device and pair again."),
        "TcpError::Timeout" to Words("The connection timed out.", "The device did not answer in time.", "Check that Ferry is open and reachable on it."),
        "TcpError::TooManyPending" to Words("The connection was refused.", "Too many devices are connecting at once.", "Wait a moment and try again."),
        "TcpError::Version" to Words("The connection was refused.", "The two devices run versions that cannot talk.", "Update Ferry on both devices."),
        "TransferError::BadPath" to Words("The transfer could not resume.", "Its saved record holds a bad path.", "Start it again."),
        "TransferError::ChunkFailedVerification" to Words("The transfer stopped.", "Part of the file did not match, at chunk {detail}. The file changed on the other device during the transfer.", "Start it again."),
        "TransferError::Local" to Words("The transfer stopped.", "This device could not write the file.", "Check free space and the shared folder."),
        "TransferError::NoRandomness" to Words("The transfer could not start.", "This device gave no random data.", "Restart Ferry."),
        "TransferError::Record" to Words("The transfer could not resume.", "Its saved record is damaged.", "Start it again. It begins from zero."),
        "TransferError::Rpc" to Words("The transfer stopped.", "The connection failed.", "It continues on its own when the device is reachable."),
        "TransferError::ShortRead" to Words("The transfer stopped.", "The other device sent less of the file than it said it holds. The file changed during the transfer.", "Start it again."),
        "VersionError::Io" to Words("The connection failed.", "The network dropped it.", "It reconnects on its own when the device is reachable."),
        "VersionError::NoSharedVersion" to Words("The connection was refused.", "The two devices run versions that cannot talk.", "Update Ferry on both devices."),
        "VersionError::NotFerry" to Words("The connection was refused.", "The other end is not Ferry.", "Check the address."),
        "VersionError::UnknownMode" to Words("The connection was refused.", "The two devices run versions that cannot talk.", "Update Ferry on both devices."),
        "WireError::BadManifest" to Words("A message could not be decoded.", "It held a manifest Ferry refuses.", "Update Ferry on both devices."),
        "WireError::InvalidPath" to Words("A message could not be decoded.", "It held a path Ferry refuses.", "Update Ferry on both devices."),
        "WireError::NotUtf8" to Words("A message could not be decoded.", "Text in it was not valid.", "Update Ferry on both devices."),
        "WireError::TooLong" to Words("A message could not be decoded.", "A field in it was too long.", "Update Ferry on both devices."),
        "WireError::TrailingBytes" to Words("A message could not be decoded.", "It had extra bytes.", "Update Ferry on both devices."),
        "WireError::UnexpectedEnd" to Words("A message could not be decoded.", "It ended early.", "Update Ferry on both devices."),
        "WireError::UnknownTag" to Words("A message could not be decoded.", "It used a tag this version does not know.", "Update Ferry on both devices."),
    )

    // Looks up the three-part words for an error code. Returns null for an
    // unknown code, which should not happen while design/errors.json is
    // complete.
    fun wordsFor(code: String): Words? = table[code]

    // Fills the {detail} placeholder in text with detail. When detail is
    // null, the placeholder is removed and any doubled space that removal
    // leaves behind is collapsed to one space.
    fun fill(text: String, detail: String?): String {
        if (detail == null) {
            var collapsed = text.replace("{detail}", "")
            while (collapsed.contains("  ")) {
                collapsed = collapsed.replace("  ", " ")
            }
            return collapsed
        }
        return text.replace("{detail}", detail)
    }
}
