// Generated by scripts/gen_tokens.py from design/tokens.json and design/colors.json. Do not edit. Change the JSON and run the script.

package app.ferry

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp

// Semantic colors for Ferry. Each function reads the right hex value for
// the current light or dark theme, so a screen never types a hex value.
object FerryColor {
    // Turns a "#rrggbb" string into a Color(0xFFrrggbb).
    private fun hex(hex: String): Color {
        val clean = hex.removePrefix("#")
        val rgb = clean.toLong(16)
        return Color(0xFF000000L or rgb)
    }

    @Composable
    private fun role(light: String, dark: String): Color {
        return if (isSystemInDarkTheme()) hex(dark) else hex(light)
    }

    @Composable
    fun background(): Color = role("#fcfcfd", "#111113")

    @Composable
    fun surface(): Color = role("#f9f9fb", "#19191b")

    @Composable
    fun surfaceRaised(): Color = role("#eff0f3", "#222325")

    @Composable
    fun border(): Color = role("#d8d9e0", "#393a40")

    @Composable
    fun borderStrong(): Color = role("#b9bbc6", "#5f606a")

    @Composable
    fun text(): Color = role("#1e1f24", "#eeeef0")

    @Composable
    fun textSecondary(): Color = role("#62636c", "#b2b3bd")

    @Composable
    fun accent(): Color = role("#3368a0", "#3368a0")

    @Composable
    fun accentHover(): Color = role("#245a90", "#245a90")

    @Composable
    fun accentSurface(): Color = role("#e7f3ff", "#0e2842")

    @Composable
    fun accentBorder(): Color = role("#9fc3ec", "#2c6199")

    @Composable
    fun accentText(): Color = role("#386da6", "#85befe")

    @Composable
    fun onAccent(): Color = role("#ffffff", "#ffffff")
}

// Spacing steps for Ferry, in dp.
object FerrySpace {
    val s1 = 4.dp
    val s2 = 8.dp
    val s3 = 12.dp
    val s4 = 16.dp
    val s5 = 24.dp
    val s6 = 32.dp
    val s7 = 48.dp
}

// Corner radius steps for Ferry, in dp.
object FerryRadius {
    val small = 4.dp
    val medium = 8.dp
    val large = 12.dp
}

// Semantic text styles for Ferry, one per role in design/tokens.json.
object FerryFont {
    @Composable
    fun display(): TextStyle = MaterialTheme.typography.displaySmall.copy(fontWeight = FontWeight.SemiBold)

    @Composable
    fun title(): TextStyle = MaterialTheme.typography.titleLarge.copy(fontWeight = FontWeight.SemiBold)

    @Composable
    fun body(): TextStyle = MaterialTheme.typography.bodyLarge.copy(fontWeight = FontWeight.Normal)

    @Composable
    fun label(): TextStyle = MaterialTheme.typography.labelLarge.copy(fontWeight = FontWeight.Medium)

    @Composable
    fun caption(): TextStyle = MaterialTheme.typography.bodySmall.copy(fontWeight = FontWeight.Normal)

    @Composable
    fun mono(): TextStyle = MaterialTheme.typography.bodyLarge.copy(fontWeight = FontWeight.Normal, fontFeatureSettings = "tnum")
}

// Semantic icon names for Ferry. Each one is a Material Symbols name.
object FerryIcon {
    const val devicePhone = "smartphone"
    const val deviceMac = "laptop_mac"
    const val usb = "usb"
    const val wifi = "wifi"
    const val notReachable = "wifi_off"
    const val paired = "verified_user"
    const val transfer = "sync_alt"
    const val paused = "pause_circle"
    const val failed = "error"
    const val done = "check_circle"
    const val forget = "delete"
    const val settings = "settings"
    const val pair = "add_circle"
}
