#!/usr/bin/env python3
"""Generate Errors.swift and Errors.kt from design/errors.json.

Run with no arguments to write both files. Run with --check to verify the
files on disk already match what this script would write, without changing
them. CI uses --check to stop anyone from hand-editing generated code.

Only the Python standard library is used, on purpose, so this script needs
no setup beyond Python 3.

Determinism: the rows are sorted by key before they are written, so the
output does not depend on the order design/errors.json happens to list them
in. Sorting also keeps a diff small when one row changes, since rows near
it do not move.
"""

import json
import sys
from pathlib import Path

# The Kotlin package for the generated file. One constant, so it is easy to
# find and change.
PACKAGE = "app.ferry"

ROOT = Path(__file__).resolve().parent.parent
ERRORS_PATH = ROOT / "design" / "errors.json"
SWIFT_PATH = ROOT / "macos" / "Ferry" / "Generated" / "Errors.swift"
KOTLIN_PATH = ROOT / "android" / "app" / "src" / "main" / "kotlin" / "app" / "ferry" / "Errors.kt"

GENERATED_NOTICE = (
    "Generated by scripts/gen_errors.py from design/errors.json. Do not "
    "edit. Change the JSON and run the script."
)


def load_json(path):
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def error_rows(data):
    """Return the error rows from design/errors.json, sorted by key."""
    return sorted(data["errors"].items())


def escape_string(value):
    """Escape a string for a double-quoted Swift or Kotlin literal.

    Both languages use the same escapes for a backslash, a double quote, and
    the common control characters, so one function serves both generators.
    """
    out = []
    for char in value:
        if char == "\\":
            out.append("\\\\")
        elif char == '"':
            out.append('\\"')
        elif char == "\n":
            out.append("\\n")
        elif char == "\t":
            out.append("\\t")
        elif char == "\r":
            out.append("\\r")
        else:
            out.append(char)
    return "".join(out)


# ---------------------------------------------------------------------------
# Swift generation
# ---------------------------------------------------------------------------


def generate_swift(data):
    rows = error_rows(data)
    lines = []
    lines.append(f"// {GENERATED_NOTICE}")
    lines.append("")
    lines.append("import Foundation")
    lines.append("")
    lines.append("/// Words for every error Ferry can show, from design/errors.json. Each")
    lines.append("/// code maps to three parts, in order: what stopped, why, what to do.")
    lines.append("enum FerryErrors {")
    lines.append("    private static let table: [String: (stopped: String, why: String, todo: String)] = [")
    for code, parts in rows:
        key = escape_string(code)
        stopped = escape_string(parts["stopped"])
        why = escape_string(parts["why"])
        todo = escape_string(parts["todo"])
        lines.append(
            f'        "{key}": (stopped: "{stopped}", why: "{why}", todo: "{todo}"),'
        )
    lines.append("    ]")
    lines.append("")
    lines.append("    /// Looks up the three-part words for an error code. Returns nil for an")
    lines.append("    /// unknown code, which should not happen while design/errors.json is")
    lines.append("    /// complete.")
    lines.append("    static func words(for code: String) -> (stopped: String, why: String, todo: String)? {")
    lines.append("        return table[code]")
    lines.append("    }")
    lines.append("")
    lines.append("    /// Fills the `{detail}` placeholder in `text` with `detail`. When")
    lines.append("    /// `detail` is nil, the placeholder is removed and any doubled space")
    lines.append("    /// that removal leaves behind is collapsed to one space.")
    lines.append("    static func fill(_ text: String, detail: String?) -> String {")
    lines.append("        guard let detail = detail else {")
    lines.append('            var collapsed = text.replacingOccurrences(of: "{detail}", with: "")')
    lines.append('            while collapsed.contains("  ") {')
    lines.append('                collapsed = collapsed.replacingOccurrences(of: "  ", with: " ")')
    lines.append("            }")
    lines.append("            return collapsed")
    lines.append("        }")
    lines.append('        return text.replacingOccurrences(of: "{detail}", with: detail)')
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Kotlin generation
# ---------------------------------------------------------------------------


def generate_kotlin(data):
    rows = error_rows(data)
    lines = []
    lines.append(f"// {GENERATED_NOTICE}")
    lines.append("")
    lines.append(f"package {PACKAGE}")
    lines.append("")
    lines.append("// Words for every error Ferry can show, from design/errors.json. Each")
    lines.append("// code maps to three parts, in order: what stopped, why, what to do.")
    lines.append("object FerryErrors {")
    lines.append("    // One error code's three parts.")
    lines.append("    data class Words(val stopped: String, val why: String, val todo: String)")
    lines.append("")
    lines.append("    private val table: Map<String, Words> = mapOf(")
    for code, parts in rows:
        key = escape_string(code)
        stopped = escape_string(parts["stopped"])
        why = escape_string(parts["why"])
        todo = escape_string(parts["todo"])
        lines.append(
            f'        "{key}" to Words("{stopped}", "{why}", "{todo}"),'
        )
    lines.append("    )")
    lines.append("")
    lines.append("    // Looks up the three-part words for an error code. Returns null for an")
    lines.append("    // unknown code, which should not happen while design/errors.json is")
    lines.append("    // complete.")
    lines.append("    fun wordsFor(code: String): Words? = table[code]")
    lines.append("")
    lines.append("    // Fills the {detail} placeholder in text with detail. When detail is")
    lines.append("    // null, the placeholder is removed and any doubled space that removal")
    lines.append("    // leaves behind is collapsed to one space.")
    lines.append("    fun fill(text: String, detail: String?): String {")
    lines.append("        if (detail == null) {")
    lines.append('            var collapsed = text.replace("{detail}", "")')
    lines.append('            while (collapsed.contains("  ")) {')
    lines.append('                collapsed = collapsed.replace("  ", " ")')
    lines.append("            }")
    lines.append("            return collapsed")
    lines.append("        }")
    lines.append('        return text.replace("{detail}", detail)')
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def read_existing(path):
    if not path.exists():
        return None
    with open(path, "r", encoding="utf-8") as handle:
        return handle.read()


def write_file(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(content)


def main():
    check_mode = "--check" in sys.argv[1:]

    data = load_json(ERRORS_PATH)

    swift_content = generate_swift(data)
    kotlin_content = generate_kotlin(data)

    if check_mode:
        mismatches = []
        if read_existing(SWIFT_PATH) != swift_content:
            mismatches.append(str(SWIFT_PATH.relative_to(ROOT)))
        if read_existing(KOTLIN_PATH) != kotlin_content:
            mismatches.append(str(KOTLIN_PATH.relative_to(ROOT)))

        if mismatches:
            print(
                "Generated errors are out of date. Run "
                "`python3 scripts/gen_errors.py` and commit the result. "
                "Out of date: " + ", ".join(mismatches)
            )
            return 1

        print("Generated errors are up to date.")
        return 0

    write_file(SWIFT_PATH, swift_content)
    write_file(KOTLIN_PATH, kotlin_content)
    print(f"Wrote {SWIFT_PATH.relative_to(ROOT)}")
    print(f"Wrote {KOTLIN_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
