#!/usr/bin/env python3
"""Generate Tokens.swift and Tokens.kt from design/tokens.json and design/colors.json.

Run with no arguments to write both files. Run with --check to verify the
files on disk already match what this script would write, without changing
them. CI uses --check to stop anyone from hand-editing generated code.

Only the Python standard library is used, on purpose, so this script needs
no setup beyond Python 3.

Determinism: both JSON files are read fresh on every run, and Python's
json.load keeps the key order of the file it reads (this has been true
since Python 3.7). So iterating the parsed data in file order already gives
the same output every time, for the same input. Nothing here builds a set
or a hash-ordered dict, so no extra sorting step is needed to stay
deterministic. Iterating in file order also keeps the generated code in the
same order as the tables in design/tokens.json, which is easier for a
person to read.
"""

import json
import sys
from pathlib import Path

# The Kotlin package for the generated file. One constant, so it is easy to
# find and change.
PACKAGE = "app.ferry"

ROOT = Path(__file__).resolve().parent.parent
TOKENS_PATH = ROOT / "design" / "tokens.json"
COLORS_PATH = ROOT / "design" / "colors.json"
SWIFT_PATH = ROOT / "macos" / "Ferry" / "Generated" / "Tokens.swift"
KOTLIN_PATH = ROOT / "android" / "app" / "src" / "main" / "kotlin" / "app" / "ferry" / "Tokens.kt"

GENERATED_NOTICE = (
    "Generated by scripts/gen_tokens.py from design/tokens.json and "
    "design/colors.json. Do not edit. Change the JSON and run the script."
)

# Font.Weight in SwiftUI and FontWeight in Compose both have a case for each
# weight name used in tokens.json. The Swift case names are exactly the
# tokens.json words, lower case. The Kotlin case names are not, so they are
# mapped here.
KOTLIN_WEIGHT_NAMES = {
    "regular": "Normal",
    "medium": "Medium",
    "semibold": "SemiBold",
}

# Default point size for each SwiftUI text style, at the base Dynamic Type
# size. These are only used if font.family in tokens.json stops being
# "system", because Font.custom needs a starting size to scale from. They
# match Apple's published base sizes for these text styles.
SWIFT_TEXT_STYLE_BASE_SIZE = {
    "largeTitle": 34,
    "title": 28,
    "title2": 22,
    "title3": 20,
    "headline": 17,
    "subheadline": 15,
    "body": 17,
    "callout": 16,
    "footnote": 13,
    "caption": 12,
    "caption2": 11,
}


def load_json(path):
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def snake_to_camel(name):
    """Convert a snake_case token key to lowerCamelCase for Swift and Kotlin."""
    parts = name.split("_")
    return parts[0] + "".join(word.capitalize() for word in parts[1:])


def resolve_color_roles(tokens, colors):
    """Look up each color role's light and dark hex from colors.json.

    Returns a list of (role_key, light_hex, dark_hex) in the order the
    roles appear in tokens.json, skipping the "note" entry.
    """
    resolved = []
    for key, role in tokens["color_roles"].items():
        if key == "note":
            continue
        if "literal" in role:
            light_hex = role["literal"]
            dark_hex = role["literal"]
        else:
            scale = role["scale"]
            step = str(role["step"])
            light_hex = colors["light"][scale][step]
            dark_hex = colors["dark"][scale][step]
        resolved.append((key, light_hex, dark_hex))
    return resolved


def type_roles(tokens):
    """Return the type roles in tokens.json, in file order."""
    return list(tokens["type"].items())


def space_entries(tokens):
    return list(tokens["space"].items())


def radius_entries(tokens):
    return list(tokens["radius"].items())


def icon_entries(tokens):
    return [(key, value) for key, value in tokens["icons"].items() if key != "note"]


# ---------------------------------------------------------------------------
# Swift generation
# ---------------------------------------------------------------------------


def swift_font_expression(role, family):
    macos_style = role["macos"]
    weight = role["weight"]
    mono = role.get("monospaced_digits", False)

    if family == "system":
        expr = f".system(.{macos_style}, weight: .{weight})"
    else:
        # font.family is not "system", so each style uses a custom font
        # family instead of the platform default. The size below is the
        # base size for the matching text style, and relativeTo keeps
        # Dynamic Type scaling from that base.
        size = SWIFT_TEXT_STYLE_BASE_SIZE[macos_style]
        expr = f'.custom("{family}", size: {size}, relativeTo: .{macos_style}).weight(.{weight})'

    if mono:
        expr += ".monospacedDigit()"
    return expr


def generate_swift(tokens, colors):
    lines = []
    lines.append(f"// {GENERATED_NOTICE}")
    lines.append("")
    lines.append("import AppKit")
    lines.append("import SwiftUI")
    lines.append("")
    lines.append("/// Semantic colors for Ferry. Each one reads the right hex value for the")
    lines.append("/// current light or dark appearance, so a view never types a hex value.")
    lines.append("enum FerryColor {")
    lines.append("    /// Turns a \"#rrggbb\" string into an NSColor.")
    lines.append("    private static func nsColor(hex: String) -> NSColor {")
    lines.append("        var hexString = hex")
    lines.append("        if hexString.hasPrefix(\"#\") {")
    lines.append("            hexString.removeFirst()")
    lines.append("        }")
    lines.append("        var rgbValue: UInt64 = 0")
    lines.append("        Scanner(string: hexString).scanHexInt64(&rgbValue)")
    lines.append("        let red = CGFloat((rgbValue & 0xFF0000) >> 16) / 255.0")
    lines.append("        let green = CGFloat((rgbValue & 0x00FF00) >> 8) / 255.0")
    lines.append("        let blue = CGFloat(rgbValue & 0x0000FF) / 255.0")
    lines.append("        return NSColor(srgbRed: red, green: green, blue: blue, alpha: 1.0)")
    lines.append("    }")
    lines.append("")
    lines.append("    /// Builds a Color with a dynamic provider, so it picks the light or dark")
    lines.append("    /// hex value on its own, each time the appearance is resolved.")
    lines.append("    private static func role(_ light: String, _ dark: String) -> Color {")
    lines.append("        let dynamic = NSColor(name: nil) { appearance in")
    lines.append("            let isDark = appearance.bestMatch(from: [.aqua, .darkAqua]) == .darkAqua")
    lines.append("            return isDark ? nsColor(hex: dark) : nsColor(hex: light)")
    lines.append("        }")
    lines.append("        return Color(nsColor: dynamic)")
    lines.append("    }")
    lines.append("")
    for key, light_hex, dark_hex in resolve_color_roles(tokens, colors):
        name = snake_to_camel(key)
        lines.append(f'    static let {name} = role("{light_hex}", "{dark_hex}")')
    lines.append("}")
    lines.append("")
    lines.append("/// Spacing steps for Ferry, in points.")
    lines.append("enum FerrySpace {")
    for key, value in space_entries(tokens):
        lines.append(f"    static let s{key}: CGFloat = {value}")
    lines.append("}")
    lines.append("")
    lines.append("/// Corner radius steps for Ferry, in points.")
    lines.append("enum FerryRadius {")
    for key, value in radius_entries(tokens):
        lines.append(f"    static let {key}: CGFloat = {value}")
    lines.append("}")
    lines.append("")
    family = tokens["font"]["family"]
    lines.append("/// Semantic text styles for Ferry, one per role in design/tokens.json.")
    lines.append("enum FerryFont {")
    for key, role in type_roles(tokens):
        expr = swift_font_expression(role, family)
        lines.append(f"    static let {key} = Font{expr}")
    lines.append("}")
    lines.append("")
    lines.append("/// Semantic icon names for Ferry. Each one is an SF Symbol name.")
    lines.append("enum FerryIcon {")
    for key, value in icon_entries(tokens):
        name = snake_to_camel(key)
        symbol = value["macos"]
        lines.append(f'    static let {name} = "{symbol}"')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Kotlin generation
# ---------------------------------------------------------------------------


def kotlin_font_expression(role, family):
    android_style = role["android"]
    weight = role["weight"]
    mono = role.get("monospaced_digits", False)
    weight_name = KOTLIN_WEIGHT_NAMES[weight]

    copy_args = [f"fontWeight = FontWeight.{weight_name}"]
    if family != "system":
        # font.family is not "system", so a custom FontFamily is applied on
        # top of the Material 3 type scale. Add the font files under
        # res/font and build customFontFamily from them before this
        # compiles.
        copy_args.insert(0, "fontFamily = customFontFamily")
    if mono:
        copy_args.append('fontFeatureSettings = "tnum"')

    args = ", ".join(copy_args)
    return f"MaterialTheme.typography.{android_style}.copy({args})"


def generate_kotlin(tokens, colors):
    lines = []
    lines.append(f"// {GENERATED_NOTICE}")
    lines.append("")
    lines.append(f"package {PACKAGE}")
    lines.append("")
    lines.append("import androidx.compose.foundation.isSystemInDarkTheme")
    lines.append("import androidx.compose.material3.MaterialTheme")
    lines.append("import androidx.compose.runtime.Composable")
    lines.append("import androidx.compose.ui.graphics.Color")
    lines.append("import androidx.compose.ui.text.TextStyle")
    lines.append("import androidx.compose.ui.text.font.FontWeight")
    lines.append("import androidx.compose.ui.unit.dp")
    lines.append("")
    lines.append("// Semantic colors for Ferry. Each function reads the right hex value for")
    lines.append("// the current light or dark theme, so a screen never types a hex value.")
    lines.append("object FerryColor {")
    lines.append("    // Turns a \"#rrggbb\" string into a Color(0xFFrrggbb).")
    lines.append("    private fun hex(hex: String): Color {")
    lines.append('        val clean = hex.removePrefix("#")')
    lines.append("        val rgb = clean.toLong(16)")
    lines.append("        return Color(0xFF000000L or rgb)")
    lines.append("    }")
    lines.append("")
    lines.append("    @Composable")
    lines.append("    private fun role(light: String, dark: String): Color {")
    lines.append("        return if (isSystemInDarkTheme()) hex(dark) else hex(light)")
    lines.append("    }")
    lines.append("")
    for key, light_hex, dark_hex in resolve_color_roles(tokens, colors):
        name = snake_to_camel(key)
        lines.append("    @Composable")
        lines.append(f'    fun {name}(): Color = role("{light_hex}", "{dark_hex}")')
        lines.append("")
    # Remove the trailing blank line left after the last color function.
    if lines[-1] == "":
        lines.pop()
    lines.append("}")
    lines.append("")
    lines.append("// Spacing steps for Ferry, in dp.")
    lines.append("object FerrySpace {")
    for key, value in space_entries(tokens):
        lines.append(f"    val s{key} = {value}.dp")
    lines.append("}")
    lines.append("")
    lines.append("// Corner radius steps for Ferry, in dp.")
    lines.append("object FerryRadius {")
    for key, value in radius_entries(tokens):
        lines.append(f"    val {key} = {value}.dp")
    lines.append("}")
    lines.append("")
    family = tokens["font"]["family"]
    lines.append("// Semantic text styles for Ferry, one per role in design/tokens.json.")
    lines.append("object FerryFont {")
    if family != "system":
        lines.append("    // font.family is not \"system\", so a custom FontFamily backs every")
        lines.append("    // style below. Point the Font() calls at the real resource ids.")
        lines.append(f'    private val customFontFamily = FontFamily(Font(R.font.{family.lower().replace(" ", "_")}))')
        lines.append("")
    for key, role in type_roles(tokens):
        expr = kotlin_font_expression(role, family)
        lines.append("    @Composable")
        lines.append(f"    fun {key}(): TextStyle = {expr}")
        lines.append("")
    if lines[-1] == "":
        lines.pop()
    lines.append("}")
    lines.append("")
    lines.append("// Semantic icon names for Ferry. Each one is a Material Symbols name.")
    lines.append("object FerryIcon {")
    for key, value in icon_entries(tokens):
        name = snake_to_camel(key)
        symbol = value["android"]
        lines.append(f'    const val {name} = "{symbol}"')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def read_existing(path):
    if not path.exists():
        return None
    with open(path, "r", encoding="utf-8") as handle:
        return handle.read()


def write_file(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(content)


def main():
    check_mode = "--check" in sys.argv[1:]

    tokens = load_json(TOKENS_PATH)
    colors = load_json(COLORS_PATH)

    swift_content = generate_swift(tokens, colors)
    kotlin_content = generate_kotlin(tokens, colors)

    if check_mode:
        mismatches = []
        if read_existing(SWIFT_PATH) != swift_content:
            mismatches.append(str(SWIFT_PATH.relative_to(ROOT)))
        if read_existing(KOTLIN_PATH) != kotlin_content:
            mismatches.append(str(KOTLIN_PATH.relative_to(ROOT)))

        if mismatches:
            print(
                "Generated tokens are out of date. Run "
                "`python3 scripts/gen_tokens.py` and commit the result. "
                "Out of date: " + ", ".join(mismatches)
            )
            return 1

        print("Generated tokens are up to date.")
        return 0

    write_file(SWIFT_PATH, swift_content)
    write_file(KOTLIN_PATH, kotlin_content)
    print(f"Wrote {SWIFT_PATH.relative_to(ROOT)}")
    print(f"Wrote {KOTLIN_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
